// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzj_KEDf3XgzQ7W6K8P-T3LnRRZkPAee8',
    appId: '1:968226357348:web:33f96149416a01e2dbdf71',
    messagingSenderId: '968226357348',
    projectId: 'smartgovernment-71d0c',
    authDomain: 'smartgovernment-71d0c.firebaseapp.com',
    storageBucket: 'smartgovernment-71d0c.appspot.com',
    measurementId: 'G-JCYXVZLWTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWpHsg8MCrEtoV4wp0k2UI7Tpk36_Pakg',
    appId: '1:437110431977:android:0b410169ae531fb5841078',
    messagingSenderId: '437110431977',
    projectId: 'traffic-a5a1b',
    storageBucket: 'traffic-a5a1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0DQP__fty5qfGeaBf0pYpSL6EpjK0eFo',
    appId: '1:437110431977:ios:97b955430be8f50a841078',
    messagingSenderId: '437110431977',
    projectId: 'traffic-a5a1b',
    storageBucket: 'traffic-a5a1b.appspot.com',
    iosBundleId: 'com.example.newApp00',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEhk5noEvechTK2yGwvx9EBf-L3BPb21Q',
    appId: '1:968226357348:ios:a9b07d8a5039af6ddbdf71',
    messagingSenderId: '968226357348',
    projectId: 'smartgovernment-71d0c',
    storageBucket: 'smartgovernment-71d0c.appspot.com',
    iosBundleId: 'com.example.newApp00',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzj_KEDf3XgzQ7W6K8P-T3LnRRZkPAee8',
    appId: '1:968226357348:web:82f6671f43f90ddedbdf71',
    messagingSenderId: '968226357348',
    projectId: 'smartgovernment-71d0c',
    authDomain: 'smartgovernment-71d0c.firebaseapp.com',
    storageBucket: 'smartgovernment-71d0c.appspot.com',
    measurementId: 'G-E7FFW4N0NY',
  );
}